# Project Name
TARGET = SynthV1

USE_DAISYSP_LGPL = 1

# Sources
CPP_SOURCES = SynthV1.cpp 

# Library Locations
LIBDAISY_DIR = ../../DaisyExamples/libDaisy
DAISYSP_DIR = ../../DaisyExamples/DaisySP


# Core location, and generic makefile.
SYSTEM_FILES_DIR = $(LIBDAISY_DIR)/core
include $(SYSTEM_FILES_DIR)/Makefile

